# Continuous Integration with GitHub Actions

name: module3_task0

# Controls when the workflow will run
on:
  # Triggers the workflow on push or once per day at midnight
  push:
    paths:
      - 'module3_task0/**'
  schedule:
    - cron: '0 0 * * *'

# Jobs has two steps, clone the repo and execute 'make help'
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent sequence of tasks that will be executed as par of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE
      # so your job can access it
      - name: Clone the repository
        uses: actions/checkout@v3

      # Go to the right folder and execute 'make help'
      - name: Execute the make help command
        run: |
          cd module3_task0/
          make help
