---
# Safer Collaboration with Pull Requests

name: module4_task1

# Controls when the workflow will run
on:
  # Triggers of the workflow
  push:
    branches: [master, main]
    # paths:
    # - 'module4_task1/**'
    tags:
      - '*.*.*'
  schedule:
    - cron: '0 0 * * *'

  pull_request:
    types: [opened, reopened, edited, ready_for_review]

# Jobs has eight steps
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-18.04

    # Steps represent sequence of tasks that will be executed as par of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE
      # so the job can access it
      - name: Clone the repository
        uses: actions/checkout@v3

      # Spin up a docker container and execute makefile targets
      - name: Create a docker image
        working-directory: module4_task1
        run: make build-docker
      - name: Execute make clean target
        working-directory: module4_task1
        run: docker run --rm awesome:build make clean
      - name: Execute make lint target
        working-directory: module4_task1
        run: docker run --rm awesome:build make lint
      - name: Execute make build target
        working-directory: module4_task1
        run: docker run --rm awesome:build make built
      - name: Execute make unit-tests target
        working-directory: module4_task1
        run: docker run --rm awesome:build make unit-tests
      - name: Execute make integration-tests target
        working-directory: module4_task1
        run: docker run --rm awesome:build make integration-tests

      # Archive the zip file as artifact
      - name: Archive code coverage results
        uses: actions/upload-artifact@v3
        with:
          name: Archive awesome-website.zip as artifact
          path: module4_task1/awesome-website.zip

      # Generate a release with the archive and the content of DEPLOY.md
      - name: Create a GitHub Release
        uses: softprops/action-gh-release@v1
        # if: github.event.pull_request
        if: startsWith(github.ref, 'refs/tags/')
        with:
          # tag_name: 1.0.xx
          files: |
            module4_task1/awesome-website.zip
            module4_task1/DEPLOY.md
          # body_path: module3_task3/DEPLOY.md

      # Deploy a new site on Netlify
      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v1.2
        with:
          publish-dir: 'module4_task1/dist'
          production-branch: master
          github-token: ${{ secrets.REPO_TOKEN }}
          deploy-message: "Deploy from GitHub Actions"
          enable-pull-request-comment: true
          enable-commit-comment: true
          overwrites-pull-request-comment: true
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        timeout-minutes: 1
