---
# Safer Collaboration with Pull Requests

name: module4_task1

# Controls when the workflow will run
on:
  # Triggers of the workflow
  push:
    branches: [master, main]
    # paths:
    # - 'module4_task1/**'
    tags:
      - '*.*.*'
  schedule:
    - cron: '0 0 * * *'

  pull_request:
    types: [opened, reopened, edited, ready_for_review]

# Jobs has eight steps
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-18.04

    # Steps represent sequence of tasks that will be executed as par of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE
      # so the job can access it
      - name: Clone the repository
        uses: actions/checkout@v3

      # Spin up a docker container and execute makefile targets
      - name: Create a docker image
        working-directory: module4_task1
        run: make build-docker
      - name: Execute make clean target
        working-directory: module4_task1
        run: docker run --rm awesome:build make clean
      - name: Execute make lint target
        working-directory: module4_task1
        run: docker run --rm awesome:build make lint
      - name: Execute make build target
        working-directory: module4_task1
        run: docker run --rm awesome:build make build
      - name: Execute make unit-tests target
        working-directory: module4_task1
        run: docker run --rm awesome:build make unit-tests
      - name: Execute make integration-tests target
        working-directory: module4_task1
        run: docker run --rm awesome:build make integration-tests
        
